### ISSUE TITLE
Use conda's own yaml reader

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-graph#12]
Rather than our reader since the conda one should handle more of the env vars.
I'm not certain how well this will play with explicitly packaged licenses.
From @scopatz

**Comment by CJ-Wright** [comment]
See also #4

**Comment by jakirkham** [comment]
Is this closed as it is solved or bc it a dup?

**Comment by CJ-Wright** [comment]
I think we started using the reader here: 5692489fe255c7cc00f87dea194c644f61bdc6bd

**Comment by CJ-Wright** [comment]
Although if that is not working properly please feel free to open an issue in the scripts repo. I haven't closed the os.environ issue yet (mostly because we haven't tested it yet)

**Comment by CJ-Wright** [comment]
(one of the reasons to move the issues to the scripts so that was closing issues with PRs/commits will be easier)
