### ISSUE TITLE
Be aware of pin vs. not pinned

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-graph#2]
See https://github.com/conda-forge/conda-forge.github.io/issues/428

**Comment by jakirkham** [comment]
Expect cb3 will help as we will have a list of pinned dependencies in one file.

**Comment by CJ-Wright** [comment]
Issue moved to [regro/cf-scripts #42](https://github.com/regro/cf-scripts/issues/42) via [**ZenHub**](https://www.zenhub.com/)
