### ISSUE TITLE
Support SHA1

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-graph#20]
Some repos use SHA1, we need to parse the hash type from the recipe, put it into the graph and pull it back out.
https://github.com/conda-forge/leveldb-feedstock/pull/6/files

**Comment by nicoddemus** [comment]
Oh I see my bad. Would you like me to open a new issue for it?

**Comment by CJ-Wright** [comment]
Does https://github.com/regro/cf-graph/issues/27 cover the issue? If not feel free to open up another issue.

**Comment by nicoddemus** [comment]
#27 covers it, thanks!

**Comment by CJ-Wright** [comment]
Hopefully https://github.com/regro/cf-scripts/pull/1 and https://github.com/regro/cf-scripts/pull/6 will fix this
