### ISSUE TITLE
Spoof different OSs

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-graph#21]
We may need to spoof different OSs for reading the meta.yaml (for packages which have different urls/sha for different OSs)

eg
https://github.com/conda-forge/git-lfs-feedstock/pull/6/files

**Comment by CJ-Wright** [comment]
Also https://github.com/conda-forge/git-feedstock/pull/33

**Comment by jakirkham** [comment]
IDK if you are using `conda-build` 2 or 3. If 2, I can point you to some code in `conda-smithy`/`conda-build-all` for this. If 3, there is a feature in `conda-build` that you can use.

**Comment by CJ-Wright** [comment]
Currently we are using 2, but I don't think there is any reason we can't use 3, so which ever will be easier to implement.

**Comment by jakirkham** [comment]
Probably both are easy. Will leave it up to you.

We use a function called [`fudge_subdir`]( https://github.com/conda-forge/conda-smithy/blob/v2.4.5/conda_smithy/configure_feedstock.py#L209 ) to do this in `conda-smithy` (though it will be gone in `conda-smithy` 3). In `conda-build` 3, there is a function called [`render`]( https://github.com/conda/conda-build/blob/3.6.0/conda_build/api.py#L29-L30 ).

**Comment by CJ-Wright** [comment]
Issue moved to [regro/cf-scripts #33](https://github.com/regro/cf-scripts/issues/33) via [**ZenHub**](https://www.zenhub.com/)
