### ISSUE TITLE
Clean up hash issue PRs

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-graph#27]
So in the first run we had some successes :tada: we also had some bugs :imp: 

Most of the bugs were focused on our handling of checksum hashes. Most of the problems were due to the dizzying variety of what recipes call their checksum. Additionally some issues were due to the bot just over looking md5 driven repos.

Steps forward:
1. Find all the "bad" repos, these are repos which failed and due to some issue with the version ticking (not new deps)
1. Write a script to close all the failed PRs (with a message saying sorry, we'll do better next time)
1. Fix the scripts so we can run again with less hash related issues. 
   1. 01 needs to provide the hash type
   1. 03 needs to have a wider array of the jinja replacements
   1. 03 needs to honor other checksum types
1. Run 02 and 03 again (01 got run this evening) (maybe start on Monday/Tuesday)

**Comment by CJ-Wright** [comment]
Also we need to not build it there are selectors in the source section (I don't know how to handle the selectors for different hashes out urls)

**Comment by xhochy** [comment]
Seems like https://github.com/conda-forge/asyncpg-feedstock/pull/2/files is one of the PRs where it failed due to the hash being named differently.

**Comment by nicoddemus** [comment]
Another one: https://github.com/conda-forge/aspy.yaml-feedstock/pull/2/files

**Comment by CJ-Wright** [comment]
Hopefully https://github.com/regro/cf-scripts/pull/1 and https://github.com/regro/cf-scripts/pull/6 will fix this

**Comment by CJ-Wright** [comment]
We'll try to run again by Tuesday to clean up the issues. I've compiled a list of all the repos which has issues here: https://github.com/regro/cf-graph/blob/master/redos

**Comment by nicoddemus** [comment]
Just FYI conda-forge/aspy.yaml-feedstock#3 correctly updated the hash and I just merged it. Thanks for the great work!

**Comment by CJ-Wright** [comment]
Awesome!
@justcalamari and I should finish up fixing Friday's run and be ready for another round of bumps most likely starting tomorrow. I'm planning on starting the cron jobs so this will run more continuously and smoothly.

**Comment by CJ-Wright** [comment]
Everything is running so I'm going to close.
