### ISSUE TITLE
How to deal with patches

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-graph#32]
Should we clear out patches on version bump?
@justcalamari 
@scopatz 
@isuruf

**Comment by scopatz** [comment]
What are you asking, precisely?

**Comment by CJ-Wright** [comment]
If we version bump a package, most likely the patch won't work. Should we delete the patch or should we just leave it there for the maintainers to deal with?

**Comment by CJ-Wright** [comment]
Issue moved to [regro/cf-scripts #29](https://github.com/regro/cf-scripts/issues/29) via [**ZenHub**](https://www.zenhub.com/)
