### ISSUE TITLE
track build and run reqs

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-graph#38]
This might be nice for understanding the highest build and run deps separately.

**Comment by jakirkham** [comment]
What sorts of things are you thinking about here? Are you contemplating what rebuilds of packages might be needed based on an upstream version change.

**Comment by CJ-Wright** [comment]
Yes, also separating the most build depended on packages from the most run depended on packages (maybe for stress testing).

**Comment by CJ-Wright** [comment]
Issue moved to [regro/cf-scripts #26](https://github.com/regro/cf-scripts/issues/26) via [**ZenHub**](https://www.zenhub.com/)
