### ISSUE TITLE
The jinja var for build number is ignored

### ISSUE THREAD

**Issue by ocefpaf** [regro/cf-graph#44]
See https://github.com/conda-forge/dropbox-feedstock/pull/4#discussion_r171557374

IMO we should just drop the jinja variable for build number. It is silly to have a variable that s used in one place. If that action is taken there is nothing to do in cf-graph. If not we need to fix the bot :unamused:

**Comment by dougalsutherland** [comment]
The reason I've often used it is just because it makes it harder to forget to reset the build number to 0 when you're bumping the version yourself if the build number is specified right next to the version, instead of potentially 15 lines away. It makes just as much sense as an `sha256` variable that's also only used once...

**Comment by ocefpaf** [comment]
> The reason I've often used it is just because it makes it harder to forget to reset the build number to 0 when you're bumping the version yourself if the build number is specified right next to the version, instead of potentially 15 lines away. It makes just as much sense as an sha256 variable that's also only used once (as you noted there)....

I disagree but I am more used to the conda recipe format than most people. Anyway, I don't oppose to use the jinja, but I would love to get rid of the excess, like the file extension for example :smile: 

> If both sha256 and build variables are going away in general to make life easier for bots, that's fine in that the build will definitely break if you forget to update the checksum. :)

Yeah, in like of the age of the bots all this may change :smile:

**Comment by CJ-Wright** [comment]
I think we can implement either way. I like the idea of using the bot to PR in basic maintenance to recipes (removing excess variables, fixing jinja variables (there was at least on instance of `{%set...` rather than `{% set...`).

**Comment by CJ-Wright** [comment]
Attn: @jakirkham

**Comment by CJ-Wright** [comment]
@justcalamari would you mind taking a look at this?

**Comment by CJ-Wright** [comment]
Issue moved to [regro/cf-scripts #21](https://github.com/regro/cf-scripts/issues/21) via [**ZenHub**](https://www.zenhub.com/)
