### ISSUE TITLE
pre-releases

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-graph#45]
It seems that some pre-releases are getting through.
I think we've blacklisted `rc` in new version numbers. Maybe we need to add `dev`. It might be nice if we had a format for pre-release tags.

**Comment by CJ-Wright** [comment]
Attn: @ocefpaf

**Comment by ocefpaf** [comment]
If you want to filter them out you can use pep440 to get a list of valid versions.

**Comment by CJ-Wright** [comment]
See: https://github.com/conda-forge/fiona-feedstock/pull/72

**Comment by jakirkham** [comment]
PEP440 will work with Python packages. However not all packages are Python (or follow Python versioning rules). Might be good to reach out to conda and conda-build devs about what is a good indicator of an `rc`, `dev`, ... version.

cc @kalefranz @msarahan @mingwandroid

**Comment by CJ-Wright** [comment]
Issue moved to [regro/cf-scripts #20](https://github.com/regro/cf-scripts/issues/20) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kalefranz** [comment]
How conda does versions:

* https://github.com/conda/conda/blob/cc04287c5633b623226d77f1b6a07534c1573bdb/conda/models/version.py#L33-L141
* https://github.com/conda/conda/issues/2071
