### ISSUE TITLE
Pull current version from anaconda.org

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-graph#46]
It would be good to pull the current package version from anaconda.org. See https://github.com/conda-forge/github3.py-feedstock/pull/11#discussion_r171591927

Is there an API for anaconda.org?
Attn:
@scopatz

**Comment by scopatz** [comment]
I think if you use conda seach with '*' and a the --channel option (and probably the Json option) you will get a list of all the packages

**Comment by CJ-Wright** [comment]
That is very clever!

**Comment by CJ-Wright** [comment]
Issue moved to [regro/cf-scripts #19](https://github.com/regro/cf-scripts/issues/19) via [**ZenHub**](https://www.zenhub.com/)
