### ISSUE TITLE
Subscribing to packages

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-graph#49]
Not sure how you are checking for updates currently, but you may find issue ( https://github.com/pypa/warehouse/issues/1683 ) interesting. Basically asking PyPI to include some sort of feed for subscribing to specific packages for updates.

**Comment by CJ-Wright** [comment]
That would be very cool.
Currently we troll through all of the packages looking at their upstream URLs, but having all the pypi packages managed through their own stream would be great!

**Comment by jakirkham** [comment]
By upstream URLs do you mean `home`, `dev_url`, or something else?

**Comment by CJ-Wright** [comment]
Wherever the `meta.yaml` describes `url` to be.

**Comment by CJ-Wright** [comment]
Issue moved to [regro/cf-scripts #18](https://github.com/regro/cf-scripts/issues/18) via [**ZenHub**](https://www.zenhub.com/)
