### ISSUE TITLE
version missed

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-graph#50]
https://github.com/conda-forge/plumpy-feedstock/pull/2
https://github.com/conda-forge/plumpy-feedstock/blob/master/recipe/meta.yaml#L2

**Comment by CJ-Wright** [comment]
At this point we should have a matrix of find and replaces which also includes some good regex matches (arb number of spaces) and a correcting system (normalize the output)

**Comment by jakirkham** [comment]
This becomes more important when we start to consider downstream packages that have tight version constraints on upstream packages. Admittedly that can get into a whole other can of worms finding the dependencies (w/version constraints) and using them to solve how best to update the graph.

**Comment by CJ-Wright** [comment]
I meant just normalizing the jinja2 variables.  Yes, optimal bumping on the graph would be awesome. It may even be possible as soon as we get rid of the cycles in our otherwise perfect DAG (although maybe we can excise the cycles from the DAG and handle them separately?)

**Comment by CJ-Wright** [comment]
Issue moved to [regro/cf-scripts #17](https://github.com/regro/cf-scripts/issues/17) via [**ZenHub**](https://www.zenhub.com/)
